



</Card>
         <div className="flex justify-center mt-4">
  <p className="text-sm text-gray-400 dark:text-green-400 font-semibold mb-0">
    Generated by Asadullah Shafique
  </p>
</div>
    </div>
  );
}